"""app/routers/anomaly.py — Anomaly detection endpoints."""
from typing import Optional
from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.orm import Session
from sqlalchemy import or_

from app.database import get_db
from app.dependencies import get_current_user
from app.models import User, Anomaly, MarketData
from app.schemas import AnomalyDetectRequest, AnomalyResponse, AnomalyPaginatedResponse
from app.services.anomaly_service import detect_anomaly

router = APIRouter(prefix="/anomalies", tags=["anomalies"])


@router.get("", response_model=AnomalyPaginatedResponse)
def list_anomalies(
    limit: int = Query(20, ge=1, le=100),
    offset: int = Query(0, ge=0),
    symbol: Optional[str] = Query(None, description="Filter by symbol"),
    is_anomaly: Optional[bool] = Query(None, description="Filter by anomaly status"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    List anomalies.
    Returns anomalies owned by the current user OR generated by the system user.
    """
    system_user = db.query(User).filter(User.email == "system@marketsurveillance.local").first()
    system_user_id = system_user.id if system_user else None

    query = db.query(Anomaly, MarketData).join(MarketData, Anomaly.market_data_id == MarketData.id)
    query = query.filter(
        or_(
            MarketData.user_id == current_user.id,
            MarketData.user_id == system_user_id
        )
    )

    if symbol:
        query = query.filter(MarketData.symbol == symbol.upper())
    
    if is_anomaly is not None:
        query = query.filter(Anomaly.is_anomaly == is_anomaly)
        
    total = query.count()
    results = query.order_by(Anomaly.detected_at.desc(), Anomaly.id.desc()).offset(offset).limit(limit).all()
    
    items = []
    for anomaly, md in results:
        # Convert SQLAlchemy Anomaly object to dict/Pydantic
        item_dict = anomaly.__dict__.copy()
        item_dict["symbol"] = md.symbol
        item_dict["market_timestamp"] = md.timestamp
        item_dict["market"] = md.market
        items.append(item_dict)
        
    return AnomalyPaginatedResponse(
        items=items,
        total=total,
        limit=limit,
        offset=offset
    )


@router.post("", response_model=AnomalyResponse, status_code=status.HTTP_201_CREATED)
def run_anomaly_detection(
    payload: AnomalyDetectRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Run anomaly detection on an existing market data record.
    Returns the anomaly result including the composite score.
    """
    return detect_anomaly(
        db=db,
        market_data_id=payload.market_data_id,
        user_id=current_user.id,
        threshold=payload.threshold,
    )
